In [2]:
import numpy
import cv2
import os

In [3]:
os.listdir()

['.ipynb_checkpoints',
 'Image process.ipynb',
 'New_written.png',
 'numpy Intro.ipynb',
 'pHOTO_50KB_png.png',
 'smallgray.png']

In [4]:
im=cv2.imread("smallgray.png",0)
im

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
im2 = cv2.imread("smallgray.png",1)
im2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [7]:
cv2.imwrite("New_written.png" , im2)

True

In [53]:
# Indexing and iterating through numpy array

In [9]:
im

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
im[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [11]:
im[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [12]:
im[2,4]

182

In [13]:
for i in im:
    print(i)  # Row wise accessing

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [14]:
for i in im.T:
    print(i) #columnwise accessing

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [15]:
for i in im.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [56]:
# Stacking and splitting

In [16]:
ims = numpy.hstack(im,im) # This will not give correct output, instead give it as a tuple

TypeError: hstack() takes 1 positional argument but 2 were given

In [17]:
ims = numpy.hstack((im,im))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
ims= numpy.vstack((im,im,im)) #vertically stack
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
lsth = numpy.hsplit(ims, 3)  # Since our 5 column array cannot be split equally into 3

ValueError: array split does not result in an equal division

In [26]:
hlist =  numpy.hsplit(ims , 5)
hlist   # Produces a python list of NUMPY arrays

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [29]:
vlist = numpy.vsplit(ims, 3)
vlist

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]